---
title: "Inducing Sparseness Exercise"
author: "Jeffrey Wu"
date: "2023-06-16"
output: pdf_document
---

Generate a random 12x12 covariance matrix: 

```{r}
n = 12
A = matrix(runif(n^2)*2-1, ncol=n)  
Cov12 = t(A) %*% A
Cov12 = Cov12 + (diag(12)*0.01)
```


```{r}
###Gareth's maximizing det procedure
subblock1 = Cov12[1:4,1:4]
subblock2 = Cov12[1:4,5:8]
subblock3 = Cov12[1:4,9:12]

subblock4 = Cov12[5:8,1:4]
subblock5 = Cov12[5:8,5:8]
subblock6 = Cov12[5:8,9:12]

subblock7 = Cov12[9:12,1:4]
subblock8 = Cov12[9:12,5:8]
subblock9 = Cov12[9:12,9:12]

Cov12.1 = Cov12

#Induce sparsity in subblock 6 (0s in precision matrix)

#change block 6 and 8 to maximize det (ONE BLOCK AT A TIME)
# subblock6 = t(subblock2) %*% solve(subblock1) %*% subblock3
# subblock8 = t(subblock6)
# 
# row1 = cbind(subblock1,subblock2,subblock3)
# row2 = cbind(subblock4,subblock5,subblock6)
# row3 = cbind(subblock7,subblock8,subblock9)

# Cov12.1 = rbind(row1,row2,row3)

#Induce sparsity in subblock 3 and 6 (7 and 8) (0s in precision matrix)
for(i in 1:10){
  #change block 6 and 8 to maximize det
  subblock6 = t(subblock2) %*% solve(subblock1) %*% subblock3
  subblock8 = t(subblock6)
  
  row1 = cbind(subblock1,subblock2,subblock3)
  row2 = cbind(subblock4,subblock5,subblock6)
  row3 = cbind(subblock7,subblock8,subblock9)
  
  Cov12.1 = rbind(row1,row2,row3)
  
  #update block 3 and 7 next
  subblock3 = subblock2 %*% solve(subblock5) %*% subblock6
  subblock7 = t(subblock3)
  
  row1 = cbind(subblock1,subblock2,subblock3)
  row2 = cbind(subblock4,subblock5,subblock6)
  row3 = cbind(subblock7,subblock8,subblock9)
  
  Cov12.1 = rbind(row1,row2,row3)
}

det(Cov12.1)
prec1 = solve(Cov12.1)
det(prec1)

#Can we generate data w new cov matrix? 
library(MASS) 
mu = runif(12,0,10)
df = data.frame(mvrnorm(100,mu,Cov12.1))
```


Original approach: 

```{r}
isSymmetric(Cov12)
det(Cov12)

#Heatmap of Cov12
library(reshape2)
melted_cormat <- melt(Cov12)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

library(huge)
#Generate random graph w cluster structure
clustered12 = huge.generator(n=100,d=12,graph = "cluster",g=3)
plot(clustered12)

#Grab adjacency matrix 
adj12 = clustered12$theta
adj12 = as.matrix(adj12)
adj12 = adj12+diag(12)

#Heatmap of adj12
library(reshape2)
melted_cormat <- melt(adj12)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```


```{r}
#Induce sparsity
prec1 = solve(Cov12)
det(prec1)

library(reshape2)
melted_cormat <- melt(prec1)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

prec2 = adj12 * prec1 
det(prec2)

library(reshape2)
melted_cormat <- melt(prec2)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

diag(prec2)

Sigma2.12 = solve(prec2)
det(Sigma2.12) #NOT AS LARGE AS DET FROM PETERS APPROACH
# Sigma2 = t(Sigma2) %*% Sigma2

library(reshape2)
melted_cormat <- melt(Sigma2.12)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

diag1 = Sigma2.12[1:4,1:4]
diag2 = Sigma2.12[5:8,5:8]
diag3 = Sigma2.12[9:12,9:12]

det(diag1)
det(diag2)
det(diag3)
```

```{r}
#Can we generate data w new cov matrix? 
library(MASS) 
mu = runif(12,0,10)
df = data.frame(mvrnorm(100,mu,Sigma2.12))
```



Generate a random 21x21 covariance matrix: 

```{r}
n = 21
A = matrix(runif(n^2)*2-1, ncol=n) 
Cov21 = t(A) %*% A
```


```{r}
###Gareth's maximizing det procedure
subblock1 = Cov21[1:7,1:7]
subblock2 = Cov21[1:7,8:14]
subblock3 = Cov21[1:7,15:21]

subblock4 = Cov21[8:14,1:7]
subblock5 = Cov21[8:14,8:14]
subblock6 = Cov21[8:14,15:21]

subblock7 = Cov21[15:21,1:7]
subblock8 = Cov21[15:21,8:14]
subblock9 = Cov21[15:21,15:21]

Cov21.1 = Cov21

#Induce sparsity in subblock 6 (0s in precision matrix)

#change block 6 and 8 to maximize det (ONE BLOCK AT A TIME)
# subblock6 = t(subblock2) %*% solve(subblock1) %*% subblock3
# subblock8 = t(subblock6)
# 
# row1 = cbind(subblock1,subblock2,subblock3)
# row2 = cbind(subblock4,subblock5,subblock6)
# row3 = cbind(subblock7,subblock8,subblock9)

# Cov21.1 = rbind(row1,row2,row3)

#Induce sparsity in subblock 3 and 6 (7 and 8) (0s in precision matrix)
for(i in 1:10){
  #change block 6 and 8 to maximize det
  subblock6 = t(subblock2) %*% solve(subblock1) %*% subblock3
  subblock8 = t(subblock6)
  
  row1 = cbind(subblock1,subblock2,subblock3)
  row2 = cbind(subblock4,subblock5,subblock6)
  row3 = cbind(subblock7,subblock8,subblock9)
  
  Cov21.1 = rbind(row1,row2,row3)
  
  #update block 3 and 7 next
  subblock3 = subblock2 %*% solve(subblock5) %*% subblock6
  subblock7 = t(subblock3)
  
  row1 = cbind(subblock1,subblock2,subblock3)
  row2 = cbind(subblock4,subblock5,subblock6)
  row3 = cbind(subblock7,subblock8,subblock9)
  
  Cov21.1 = rbind(row1,row2,row3)
}

det(Cov21.1)
prec1 = solve(Cov21.1)
det(prec1)

#Can we generate data w new cov matrix? 
library(MASS) 
mu = runif(21,0,10)
df = data.frame(mvrnorm(100,mu,Cov21.1))
```


Original approach: 

```{r}
isSymmetric(Cov21)
det(Cov21)

#Heatmap of Cov21
library(reshape2)
melted_cormat <- melt(Cov21)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

library(huge)
#Generate random graph w cluster structure
clustered21 = huge.generator(n=100,d=21,graph = "cluster",g=3)
plot(clustered21)

#Grab adjacency matrix 
adj21 = clustered21$theta
adj21 = as.matrix(adj21)
adj21 = adj21+diag(21)

#Heatmap of adj21
library(reshape2)
melted_cormat <- melt(adj21)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```


```{r}
#Induce sparsity
prec1 = solve(Cov21)
det(prec1)

library(reshape2)
melted_cormat <- melt(prec1)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

prec2 = adj21 * prec1 
det(prec2)

library(reshape2)
melted_cormat <- melt(prec2)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

diag(prec2)

Sigma2.21 = solve(prec2)
det(Sigma2.21)
# Sigma2 = t(Sigma2) %*% Sigma2

library(reshape2)
melted_cormat <- melt(Sigma2.21)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

diag1 = Sigma2.21[1:7,1:7]
diag2 = Sigma2.21[8:14,8:14]
diag3 = Sigma2.21[15:21,15:21]

det(diag1)
det(diag2)
det(diag3)
```

```{r}
#Can we generate data w new cov matrix? 
library(MASS) 
mu = runif(21,0,10)
df = data.frame(mvrnorm(100,mu,Sigma2.21)) #not positive definite so doesn't work 
```


