---
title: "SKATER Validation 2"
author: "Jeffrey Wu"
date: "2023-05-31"
output: pdf_document
---

```{r}
library(huge)

#Generate random graph w cluster structure
clustered58 = huge.generator(n=100,d=58,graph = "cluster",g=5)
plot(clustered58)

#Grab adjacency matrix 
adj58 = clustered58$theta
adj58 = as.matrix(adj58)

#Grab sample covariance from huge.data
huge.data = clustered58$data
huge.means = colMeans(huge.data)
```


Run SKATER on newly generated hospitalizations data: 

SKATER clustering: 

```{r}
###Setting up SPDF for CA counties 
CA_sf = st_read(getwd(),"CA_Counties_TIGER2016")
CA_spdf = as_Spatial(CA_sf)

scaled_data = scale(huge.means)
covariates_scale = data.frame(scaled_data)

CA_spdf@data = covariates_scale

#Identify neighborhood list for counties 
CA_nb = poly2nb(CA_spdf)

# plot(CA_spdf, main = "With queen")
# plot(CA_nb, coords = coordinates(CA_spdf), col="blue", add = TRUE)

#Calculate edge costs (dissimilarity matrix) based on Euclidean distance 
costs <- nbcosts(CA_nb, data = covariates_scale)

###Get adjacency matrix using nb2mat() (SEPARATE STEP FOR INLA)
#adj = nb2mat(CA_nb,style = "B")

#Transform edge costs to spatial weights 
ct_w <- nb2listw(CA_nb,costs,style="B")

#Create minimum spanning tree 
ct_mst <- mstree(ct_w)

#Run SKATER algorithm to get 5 contiguous clusters (cluster idx is in order of CA_sf)
clus5 <- skater(edges = ct_mst[,1:2], data = covariates_scale, ncuts = 4)

#Plot clustered CA
plot((CA_sf %>% mutate(clus = clus5$groups))['clus'], main = "5 cluster from SKATER")

clus5groups = clus5$groups

#Hardcode adj matrix corresponding w SKATER clustering 
adj58.est = matrix(NA,nrow = 58,ncol=58)

for (i in 1:58){
  for (j in 1:58){
    if (i == j){
      adj58.est[i,j] = 0
    }
    
    else if (clus5groups[i] != clus5groups[j]){
      adj58.est[i,j] = 0
    }
    
    else if(clus5groups[i] == clus5groups[j]){
      adj58.est[i,j] = 1
    }
  }
}

norm(adj58.est)  
norm(adj58)
```




