---
title: "Synthetic data fitting"
author: "Jeffrey Wu"
date: "2023-10-30"
output: html_document
---

## Poisson data with fixed intensity and seasonal pattern 

```{r}
library(astsa)
set.seed(10)

# Set the fixed intensity
lambda <- 5
time_intervals <- 1:72

# Define a monthly sine wave pattern for seasonality
seasonal_pattern <- sin(2 * pi * time_intervals / 12) + lambda

# Simulate Poisson data with seasonality
simulated_data <- rpois(72,seasonal_pattern)

# Print the simulated data
tsplot(simulated_data)
```

INLA model 1: Poisson GLMM

```{r}
months = rep(1:12,6)
id = rep(1,72)

simulated_data = data.frame(months,id,simulated_data)
simulated_data$months = factor(simulated_data$months)
colnames(simulated_data)[3] = "response"

formula1 = response ~ months + f(id,model = "iid")
model1 = inla(formula1,family = "poisson",data = simulated_data)

#Get model summaries
model1$summary.fixed
bri.hyperpar.summary(model1)

#Exponentiating parameter to get better interpretation of estimates 
multeff <- exp(model1$summary.fixed$mean)
names(multeff) <- model1$names.fixed
multeff

preds_model1 = model1$summary.fitted.values
tsplot(round(preds_model1$mean))
```

## Poisson data with deterministic intensity (sinusoidal) and seasonal pattern 

```{r}
# Define a time-dependent intensity function (e.g., a linear increase)
lambda0 <- 5
slope = 2.5
time_intervals <- 1:72
time_trend = (time_intervals/72)*slope + lambda0

# Define a monthly sine wave pattern for seasonality
seasonal_pattern <- sin(2 * pi * time_intervals / 12)

# Simulate Poisson data with seasonality
simulated_data1 <- rpois(72, time_trend + seasonal_pattern)

# Print the simulated data
tsplot(simulated_data1)
```

INLA model 1: Poisson GLMM

```{r}
simulated_data1 = data.frame(months,id,simulated_data1)
simulated_data1$months = factor(simulated_data1$months)
colnames(simulated_data1)[3] = "response"

formula1 = response ~ months + f(id,model = "iid")
model1 = inla(formula1,family = "poisson",data = simulated_data1)

#Get model summaries
model1$summary.fixed
bri.hyperpar.summary(model1)

#Exponentiating parameter to get better interpretation of estimates 
multeff <- exp(model1$summary.fixed$mean)
names(multeff) <- model1$names.fixed
multeff

preds_model1 = model1$summary.fitted.values
tsplot(round(preds_model1$mean))
```

## LGCP data 

```{r}
library(MASS)
library(mvtnorm)
library(huge)

#Simulate data with some sparsity structure
data = huge.generator(n=72,d=8,graph="cluster")
plot(data)

#Grab sample covariance matrix and generate MVN data with it 
scov = data$sigmahat
adj = data$theta
adj = as.matrix(adj)
simulated_data4 = mvrnorm(n=72,rep(log(5),8),scov) #set avg intensity to 5 

pois_rates = exp(simulated_data4)

simulated_data4 = apply(pois_rates,2,rpois,n=72)

tsplot(simulated_data4[,4])

cox_data = simulated_data4[,1]
for (i in 2:8){
  cox_data = c(cox_data,simulated_data4[,i])
}
```

INLA model 1: Poisson GLMM

```{r}
id = rep(1:8,each = 72)
id2 = 1:576
months = rep(1:12,48)

simulated_data4 = data.frame(months,id,id2,cox_data)
simulated_data4$months = factor(simulated_data4$months)
colnames(simulated_data4)[4] = "response"

### Multiple response by cluster pops / 100,000###

formula1 = response ~ months + f(id,model = "iid")
model1 = inla(formula1,family = "poisson",data = simulated_data4)

#Get model summaries
model1$summary.fixed
bri.hyperpar.summary(model1)

#Exponentiating parameter to get better interpretation of estimates 
multeff <- exp(model1$summary.fixed$mean)
names(multeff) <- model1$names.fixed
multeff

preds_model1 = model1$summary.fitted.values
# preds_model1$mean = round(preds_model1$mean)
preds_model1 = cbind(simulated_data4$id,preds_model1)
colnames(preds_model1) = c("id","mean","sd","0.025quant",
                               "0.5quant","0.975quant","mode")

for (i in 1:8){
  df = preds_model1 %>% filter(id == i)
  tsplot(df$mean)
}
```

INLA model 2: BYM model

```{r}
formula2 = response ~ months + f(id, model = "bym", graph = adj) 
model2 = inla(formula2,family = "poisson",data = simulated_data4)

#Get model summaries
model2$summary.fixed
bri.hyperpar.summary(model2)

#Exponentiating parameter to get better interpretation of estimates 
multeff <- exp(model2$summary.fixed$mean)
names(multeff) <- model2$names.fixed
multeff

preds_model2 = model2$summary.fitted.values
# preds_model2$mean = round(preds_model2$mean)
preds_model2 = cbind(simulated_data4$id,preds_model2)
colnames(preds_model2) = c("id","mean","sd","0.025quant",
                               "0.5quant","0.975quant","mode")

for (i in 1:8){
  df = preds_model2 %>% filter(id == i)
  tsplot(df$mean)
}
```

INLA model w generic0 setting: 

```{r}
kgr_formula1 = response ~ months + f(id,model = "generic0",Cmatrix = scov)
# kgr_formula2 = response ~ f(id2,model = "generic0",Cmatrix = scov) #doesn't work w id2, works for id 
kgr_model = inla(kgr_formula1, data = simulated_data4, family = "poisson")

kgr_model$summary.fixed
bri.hyperpar.summary(kgr_model)

#Exponentiating parameter to get better interpretation of estimates 
multeff <- exp(kgr_model$summary.fixed$mean)
names(multeff) <- kgr_model$names.fixed
multeff

preds_kgr = kgr_model$summary.fitted.values
# preds_kgr$mean = round(preds_kgr$mean)
preds_kgr = cbind(simulated_data4$id,preds_kgr)
colnames(preds_kgr) = c("id","mean","sd","0.025quant",
                               "0.5quant","0.975quant","mode")

for (i in 1:8){
  df = preds_kgr %>% filter(id == i)
  tsplot(df$mean)
}
```